In [1]:
import pandas as pd
import numpy as np

In [3]:
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
in9=np.arange(0,100,3,)
in9

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
in9.size

34

In [12]:
in11=np.random.rand(3,5)
in11

array([[0.60083857, 0.51088752, 0.1948614 , 0.18355847, 0.7953048 ],
       [0.67051607, 0.73820648, 0.26282508, 0.94326928, 0.39499514],
       [0.79528846, 0.99795463, 0.98533483, 0.23433015, 0.73251496]])

In [13]:
np.random.seed(42)
int12=np.random.randint(0,10,size=(4,6))
int12

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [22]:
yoyo=np.random.randint(0,10,size=(3,5))



yoyo

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [23]:
np.argsort(yoyo)

array([[3, 2, 4, 0, 1],
       [0, 3, 2, 4, 1],
       [4, 2, 0, 3, 1]], dtype=int64)