In [1]:
import numpy as np

## DataTypes & Attribute

In [2]:
# Numpy's main datatype is ndarray(N-dimentional array)
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],
            [4,5,6]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
           [[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [10]:
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [11]:
sample_array=np.array([1,2,3,])

In [12]:
sample_array

array([1, 2, 3])

In [13]:
ones=np.ones((2,3))

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
random_array=np.arange(0,20,1)
random_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[4, 3, 7, 0, 4],
       [2, 7, 8, 3, 2],
       [9, 0, 3, 9, 0]])

In [18]:
random_array2=np.random.random((5,3))
random_array2

array([[0.62959103, 0.09617108, 0.22785398],
       [0.55513532, 0.69903004, 0.23940396],
       [0.5824873 , 0.91005529, 0.19547777],
       [0.31004409, 0.68134331, 0.29070003],
       [0.3057788 , 0.73219757, 0.7378719 ]])

In [19]:
random_array3=np.random.random((5,3))*10

In [20]:
random_array3

array([[4.87132619, 0.23450793, 3.22319728],
       [2.28824621, 4.41383835, 2.67973683],
       [1.83904262, 0.44555593, 8.19775796],
       [0.37872192, 7.40874438, 8.16663209],
       [7.50934433, 8.50405928, 9.85121281]])

## 3. viewing arrays and matrices

In [21]:
np.unique(random_array3)

array([0.23450793, 0.37872192, 0.44555593, 1.83904262, 2.28824621,
       2.67973683, 3.22319728, 4.41383835, 4.87132619, 7.40874438,
       7.50934433, 8.16663209, 8.19775796, 8.50405928, 9.85121281])

## 4.Manipulating & comparing arrays

### Arithmetic

In [22]:
a1

array([1, 2, 3])

In [23]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
#how can you reshape a2 to be compatible with a3
#search: "How to reshape numpy array"
#a2*a3
a4=a3.reshape(3,6)
#a4
np.dot(a2,a4)

array([[ 54,  60,  66,  72,  78,  84],
       [117, 132, 147, 162, 177, 192]])

### Dot Product

In [26]:
np.random.seed(0)

mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [28]:
# Element-wise multiplication (Hademard Product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [29]:
# Dot Product 
#np.dot(mat1,mat2)

In [30]:
#transpose mat1
mat1.T


array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [31]:
mat1.T.shape

(3, 5)

In [32]:
mat3=np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot product Example(Nut butter sales)

In [33]:
np.random.seed(0)
#number of jars sold
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [34]:
#Create Weekly_sales DataFrame
weekly_sales=pd.DataFrame(sales_amounts,
                          index=["Mon","Tue","Wed","Thu","Fri"],
                          columns=["Almond butter","Peanut butter","Cashew butter"])

In [35]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [36]:
#Create prices array
prices=np.array([10,8,12])
prices

array([10,  8, 12])

In [37]:
#Create butter_price Dataframe
butter_price=pd.DataFrame(prices.reshape(1,3),
                         index=["Price"],
                          columns=["Almond butter","Peanut butter","Cashew butter"])
butter_price


Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [38]:
total_sales=np.dot(prices,sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [39]:
#Create daily_sales
butter_price

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [40]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [41]:
daily_sales=butter_price.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thu  Fri
Price  240  138  458  232  142

In [42]:
weekly_sales["Total ($)"]=daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142

In [43]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [45]:
bool_array=a1>a2
bool_array

array([[False, False, False],
       [False, False, False]])

In [46]:
a1>5

array([False, False, False])

In [47]:
a1<5

array([ True,  True,  True])

## 5. Sorting Arrays

In [50]:
random_array=np.random.randint(10,size=(3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [51]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [60]:
## used to sort indices 
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [62]:
random_array.shape

(3, 5)

## 6. Practical Example- NumPy in action

<img src="images/panda.png"/>

In [72]:
# Turn an image into a numpy array
from matplotlib.image import imread
panda=imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [73]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [78]:
# panda.size,
panda.shape


(2330, 3500, 3)

In [80]:
random_array=np.random.randint(10,size=(3,5))
random_array

array([[4, 4, 3, 4, 4],
       [8, 4, 3, 7, 5],
       [5, 0, 1, 5, 9]])

In [81]:
random_array.dtype

dtype('int32')

In [87]:
dataframe1=pd.DataFrame(random_array,index=['row1','row2','row3'],columns=["Col1","Col2","Col3","Col4","Col5",])
dataframe1

Col1  Col2  Col3  Col4  Col5
row1     4     4     3     4     4
row2     8     4     3     7     5
row3     5     0     1     5     9